project:
  type: website
  output-dir: docs

website:
  title: "angel's blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

